[project]
name = "embrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "extensions>=0.4",
    "numpy>=2.3.3",
    "typing>=3.10.0.0",
    "typing-extensions>=4.15.0",
]
